name: oggetto
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  mask_text_input_formatter: ^2.4.0
  flutter_scale_tap: ^1.0.5
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  formz: ^0.4.1
  google_fonts: ^3.0.1
  firebase_core: ^2.1.0
  firebase_auth: ^4.0.2
  firebase_database: ^10.0.6
  dartz: ^0.10.1
  convex_bottom_bar: ^3.1.0+1
  firebase_storage: ^11.0.6
  file_picker: ^5.2.2
  uuid: ^3.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/

